version: '3'
services:
  backend:
    restart: always
    container_name: silicat-backend
    build:
      context: ./scanner-silicat-back
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://database-container:3306/barcode
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    

  frontend:
    build:
      context: ./scanner-silicat
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://127.0.0.1:8080/api/

  mysql:
    image: mysql:latest
    container_name: database-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: barcode
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
